#!/usr/bin/env python3
"""Quality gate for SKILL.md files (see SKILL_TEMPLATE.md beside this skill).

This validator is self-contained: it does not read any repo-global docs. The
authoring contract lives in `<stack>-skill-creator/SKILL_TEMPLATE.md`.

Fails (exit non-zero) when a skill:
  * is missing any required section / frontmatter field,
  * contains a banned placeholder phrase,
  * has fewer than 5 Bad or 5 Good examples,
  * has an empty or comment-only code fence,
  * references a `related:` / [[...]] target that does not resolve to a real skill,
  * is not byte-identical across the three agent dirs (.agents/.claude/.gemini).

Usage
-----
    python validate.py --stack express          # validate one stack (all 3 agent dirs)
    python validate.py --all                     # validate every stack
    python validate.py --stack express --report  # don't fail; just summarise slop counts
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

AGENT_DIRS = (".agents", ".claude", ".gemini")
CANONICAL_AGENT = ".claude"

REQUIRED_SECTIONS = [
    "## Safety contract: non-negotiable",
    "## Required tools",
    "## Gotchas",
    "## Workflow",
    "## Code Examples (Good vs Bad)",
    "## Related skills",
]

BANNED_PHRASES = [
    "Targeted domain-specific sub-skill",
    "Verified secure execution paths",
    "Draft implementation blueprint",
    "Optimize configuration attributes",
    "Run local unit tests assertions",
    "Poin arsitektur tingkat tinggi",
    "Autogenerated sub-skill",
    "Missing boundaries verification",
]

FENCE_RE = re.compile(r"```[^\n]*\n(.*?)```", re.DOTALL)
LINK_RE = re.compile(r"\[\[([a-z0-9-]+)\]\]")
TODO_RE = re.compile(r"\bTODO\b")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[5]


def fence_is_empty(body: str) -> bool:
    """A fence is 'empty' if every non-blank line is a comment or placeholder."""
    meaningful = []
    for line in body.splitlines():
        s = line.strip()
        if not s:
            continue
        if s.startswith(("//", "#", "--", "/*", "*", "<!--")):
            continue
        if s in ("...", "…"):
            continue
        meaningful.append(s)
    return not meaningful


def frontmatter(text: str) -> tuple[dict, str]:
    if not text.startswith("---"):
        return {}, text
    end = text.find("\n---", 3)
    if end == -1:
        return {}, text
    raw = text[3:end].strip("\n")
    body = text[end + 4 :]
    meta: dict = {}
    key = None
    for line in raw.splitlines():
        if re.match(r"^\s*-\s+", line) and key:
            meta.setdefault(key, []).append(line.strip()[2:].strip())
        elif ":" in line:
            key, _, val = line.partition(":")
            key = key.strip()
            val = val.strip()
            meta[key] = val if val else []
    return meta, body


def existing_slugs(stack: str, agent: str, root: Path) -> set[str]:
    base = root / stack / agent / "skills"
    if not base.exists():
        return set()
    return {p.name for p in base.iterdir() if (p / "SKILL.md").exists()}


def validate_file(path: Path, slug: str, slugs: set[str]) -> list[str]:
    errors: list[str] = []
    text = path.read_text(encoding="utf-8")

    meta, body = frontmatter(text)
    if not meta:
        errors.append("missing/invalid YAML frontmatter")
    if meta.get("name") not in (slug, None) and meta.get("name") != slug:
        errors.append(f"frontmatter name '{meta.get('name')}' != dir '{slug}'")
    desc = meta.get("description", "")
    if not isinstance(desc, str) or len(desc.strip()) < 12:
        errors.append("description missing or too short")

    for phrase in BANNED_PHRASES:
        if phrase in text:
            errors.append(f"banned placeholder phrase: '{phrase}'")
    if TODO_RE.search(text):
        errors.append("contains unfilled TODO")

    for section in REQUIRED_SECTIONS:
        if section not in text:
            errors.append(f"missing section: {section}")

    bad = len(re.findall(r"^### Bad Example", text, re.MULTILINE))
    good = len(re.findall(r"^### Good Example", text, re.MULTILINE))
    if bad < 5:
        errors.append(f"need >=5 Bad examples (found {bad})")
    if good < 5:
        errors.append(f"need >=5 Good examples (found {good})")

    for i, fence in enumerate(FENCE_RE.findall(text), 1):
        if fence_is_empty(fence):
            errors.append(f"code fence #{i} is empty/comment-only")

    # cross-link resolution
    for target in set(LINK_RE.findall(text)):
        if target not in slugs:
            errors.append(f"[[{target}]] does not resolve to an existing skill")
    for target in meta.get("related", []) or []:
        if isinstance(target, str) and target and target not in slugs:
            errors.append(f"related '{target}' does not resolve to an existing skill")

    return errors


def check_sync(stack: str, slug: str, root: Path) -> list[str]:
    """Verify SKILL.md is byte-identical across the three agent dirs."""
    contents = {}
    for agent in AGENT_DIRS:
        f = root / stack / agent / "skills" / slug / "SKILL.md"
        if f.exists():
            contents[agent] = f.read_text(encoding="utf-8")
    if len(contents) < 2:
        return []
    ref_agent, ref = next(iter(contents.items()))
    return [
        f"out of sync: {agent} differs from {ref_agent}"
        for agent, c in contents.items()
        if c != ref
    ]


def validate_stack(stack: str, root: Path, report: bool) -> int:
    slugs = existing_slugs(stack, CANONICAL_AGENT, root)
    if not slugs:
        print(f"{stack}: no skills found", file=sys.stderr)
        return 1

    total_errors = 0
    slop_skills = 0
    base = root / stack / CANONICAL_AGENT / "skills"
    for slug in sorted(slugs):
        path = base / slug / "SKILL.md"
        errs = validate_file(path, slug, slugs)
        errs += check_sync(stack, slug, root)
        if errs:
            slop_skills += 1
            total_errors += len(errs)
            if not report:
                print(f"\nFAIL {stack}/{slug}:")
                for e in errs:
                    print(f"  - {e}")

    clean = len(slugs) - slop_skills
    print(
        f"\n{stack}: {clean}/{len(slugs)} skills pass, "
        f"{slop_skills} need work ({total_errors} issues)."
    )
    if report:
        return 0
    return 1 if total_errors else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate SKILL.md quality.")
    parser.add_argument("--stack", help="Stack to validate (e.g. express)")
    parser.add_argument("--all", action="store_true", help="Validate all stacks")
    parser.add_argument(
        "--report", action="store_true", help="Summarise only; always exit 0"
    )
    args = parser.parse_args(argv)
    root = repo_root()

    if args.all:
        stacks = sorted(
            p.name
            for p in root.iterdir()
            if p.is_dir() and (p / CANONICAL_AGENT / "skills").exists()
        )
    elif args.stack:
        stacks = [args.stack]
    else:
        parser.error("pass --stack <name> or --all")

    rc = 0
    for stack in stacks:
        rc |= validate_stack(stack, root, args.report)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
